export { LandingPage } from './LandingPage'
export { PatientPortal } from './PatientPortal'
export { HospitalPortal } from './HospitalPortal'
export { AIResearchPortal } from './AIResearchPortal'
export { Whitepaper } from './Whitepaper'
export { VerifierPortal } from './VerifierPortal'
